import type { Metadata } from 'next';
import './globals.css';
import { Container } from '@/components/Container';
import { Header } from '@/components/Header';
import { Footer } from '@/components/Footer';
import { ToastifyContainer } from '@/components/toastify-container';

export const metadata: Metadata = {
  title: {
    default: 'The Blog - Um blog em Next.js',
    template: '%s |The Blog',
  },
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='pt-BR'>
      <body>
        <Container>
          <Header />

          {children}
          <Footer />
        </Container>

        <ToastifyContainer />
      </body>
    </html>
  );
}
